/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onestyle;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author BRENDA
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        irCrearCBtn = new javax.swing.JButton();
        inciarSBtn = new javax.swing.JButton();
        contraseñaPf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onestyle/logooooo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 20, 420, 240);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        irCrearCBtn.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        irCrearCBtn.setText("Create una");
        irCrearCBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        irCrearCBtn.addActionListener(this::irCrearCBtnActionPerformed);
        jPanel1.add(irCrearCBtn);
        irCrearCBtn.setBounds(830, 340, 140, 40);

        inciarSBtn.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        inciarSBtn.setText("Iniciar sesion");
        inciarSBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        inciarSBtn.addActionListener(this::inciarSBtnActionPerformed);
        jPanel1.add(inciarSBtn);
        inciarSBtn.setBounds(760, 210, 180, 100);

        contraseñaPf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contraseñaPf.addActionListener(this::contraseñaPfActionPerformed);
        jPanel1.add(contraseñaPf);
        contraseñaPf.setBounds(140, 330, 460, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel4.setText("CONTRASEÑA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 290, 220, 32);

        correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(correoTxt);
        correoTxt.setBounds(140, 190, 460, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setText("CORREO");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 140, 200, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setText("INICIAR SESION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 290, 70);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 2, 18)); // NOI18N
        jLabel6.setText("¿No tienes cuenta?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(680, 340, 150, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 2, 14)); // NOI18N
        jLabel7.setText("Inicia sesion para entrar a la pagina");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 30, 290, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 300, 1050, 420);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onestyle/fondo.jpg.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contraseñaPfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaPfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaPfActionPerformed

    private void inciarSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inciarSBtnActionPerformed
String correo = correoTxt.getText();
    String contrasena = new String(contraseñaPf.getPassword());

    boolean encontrado = false;

    try {

    try (BufferedReader lector = new BufferedReader(new FileReader("usuarioss.txt"))) {
        String linea;

        while ((linea = lector.readLine()) != null) {

            String[] datos = linea.split(",");

            String usuarioGuardado = datos[1];
            String contrasenaGuardada = datos[2];

            if (correo.equals(usuarioGuardado) && contrasena.equals(contrasenaGuardada)) {

                Sesion.nombre = datos[0];
                Sesion.correo = datos[1];
                Sesion.contraseña = datos[2];
    
                encontrado = true;
                break;

            }

        }
    }

        if (encontrado) {

            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso");

            Catalogo catalogo = new Catalogo();
            catalogo.setVisible(true);

            this.dispose();

        } else {

            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos");

        }

    } catch (IOException e) {

        JOptionPane.showMessageDialog(this, "Error al leer usuarios");

    }
    }//GEN-LAST:event_inciarSBtnActionPerformed

    private void irCrearCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irCrearCBtnActionPerformed
Registro Registro = new Registro();
Registro.setVisible(true);

this.dispose();
    }//GEN-LAST:event_irCrearCBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaPf;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JButton inciarSBtn;
    private javax.swing.JButton irCrearCBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
