/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onestyle;

import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author BRENDA
 */
public class Registro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        irLoginBtn = new javax.swing.JButton();
        contraseñaPf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        crearCBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onestyle/logooooo.png"))); // NOI18N
        jLabel6.setText("jLabel5");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 60, 390, 250);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        irLoginBtn.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        irLoginBtn.setText("iniciar sesion");
        irLoginBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        irLoginBtn.addActionListener(this::irLoginBtnActionPerformed);
        jPanel2.add(irLoginBtn);
        irLoginBtn.setBounds(800, 288, 130, 50);

        contraseñaPf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(contraseñaPf);
        contraseñaPf.setBounds(150, 320, 420, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(150, 290, 220, 32);

        correoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        correoTxt.addActionListener(this::correoTxtActionPerformed);
        jPanel2.add(correoTxt);
        correoTxt.setBounds(150, 230, 420, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel3.setText("Correo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 190, 170, 32);

        usuarioTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(usuarioTxt);
        usuarioTxt.setBounds(150, 150, 420, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 110, 170, 32);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel1.setText("REGISTRO");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(13, 7, 136, 32);

        crearCBtn.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        crearCBtn.setText("Crear cuenta");
        crearCBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        crearCBtn.addActionListener(this::crearCBtnActionPerformed);
        jPanel2.add(crearCBtn);
        crearCBtn.setBounds(680, 150, 160, 90);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 2, 14)); // NOI18N
        jLabel7.setText("Crea tu cuenta para acceder a todos los beneficios");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(13, 45, 314, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 2, 18)); // NOI18N
        jLabel8.setText("¿Ya tienes cuenta?");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(650, 290, 170, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(160, 330, 1040, 380);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onestyle/fondo.jpg.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtActionPerformed

    private void crearCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCBtnActionPerformed
try {

    FileWriter archivo = new FileWriter("usuarios.txt", true);

    String usuario = usuarioTxt.getText();
    String correo = correoTxt.getText();
    String contraseña;
    contraseña = new String(contraseñaPf.getPassword());

    archivo.write(usuario + "," + correo + "," + contraseña + "\n");

    archivo.close();

    JOptionPane.showMessageDialog(this, "Cuenta creada correctamente");
    
    Login login = new Login();
    login.setVisible(true);

    this.dispose();

    usuarioTxt.setText("");
    correoTxt.setText("");
    contraseñaPf.setText("");

} catch (IOException e) {

    JOptionPane.showMessageDialog(this, "Error al guardar usuario");

}
    }//GEN-LAST:event_crearCBtnActionPerformed

    private void irLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irLoginBtnActionPerformed
Login login = new Login();
login.setVisible(true);

this.dispose();
    }//GEN-LAST:event_irLoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñaPf;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JButton crearCBtn;
    private javax.swing.JButton irLoginBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
